# Russian River Step 2 -- simulation geometry 

In this step we will form the map-view simulation geometry.

In [1]:
# these can be turned on for development work
%load_ext autoreload
%autoreload 2

In [2]:
# setting up logging first or else it gets preempted by another package
import watershed_workflow.ui
watershed_workflow.ui.setup_logging(1)

In [3]:
import os,sys
import logging
import numpy as np
from matplotlib import pyplot as plt
import shapely
import pandas as pd
import geopandas as gpd
pd.options.display.max_columns = None

import watershed_workflow 
import watershed_workflow.config
import watershed_workflow.sources
import watershed_workflow.mesh
import watershed_workflow.regions
import watershed_workflow.resampling

# set the default figure size for notebooks
plt.rcParams["figure.figsize"] = (8, 6)

## Input: Parameters and other source data

In [4]:
# Force Watershed Workflow to pull data from this directory rather than a shared data directory.
# This picks up the Coweeta-specific datasets set up here to avoid large file downloads for 
# demonstration purposes.
#
def splitPathFull(path):
    """
    Splits an absolute path into a list of components such that
    os.path.join(*splitPathFull(path)) == path
    """
    parts = []
    while True:
        head, tail = os.path.split(path)
        if head == path:  # root on Unix or drive letter with backslash on Windows (e.g., C:\)
            parts.insert(0, head)
            break
        elif tail == path:  # just a single file or directory
            parts.insert(0, tail)
            break
        else:
            parts.insert(0, tail)
            path = head
    return parts

cwd = splitPathFull(os.getcwd())
assert cwd[-1] == 'workflow'
cwd = cwd[:-1]

# Note, this directory is where downloaded data will be put as well
data_dir = os.path.join(*(cwd + ['input_data',]))
def toInput(filename):
    return os.path.join(data_dir, filename)

output_dir = os.path.join(*(cwd + ['output_data',]))
output_filenames = dict()
def fromOutput(filename):
    return os.path.join(output_dir, filename)    

def toOutput(role, filename):
    output_filenames[role] = filename
    return fromOutput(filename)

# check output and input dirs exist
if not os.path.isdir(data_dir):
    os.makedirs(data_dir, exist_ok=True)
if not os.path.isdir(output_dir):
    os.makedirs(output_dir, exist_ok=True)

In [5]:
# Set the data directory to the local space to get the locally downloaded files
# REMOVE THIS CELL for general use outside fo Coweeta
watershed_workflow.config.setDataDirectory(data_dir)

In [6]:
## Parameters cell -- this provides all parameters that can be changed via pipelining to generate a new watershed. 
name = 'RussianRiver'
hucs = ['18010110'] # a list of HUCs to run

# Geometric parameters
# -- parameters to clean and reduce the river network prior to meshing
prune_by_area = 20               # km^2
simplify = 200                   # length scale to target average edge 

# -- mesh triangle refinement control
refine_d0 = 200
refine_d1 = 600

refine_L0 = 200
refine_L1 = 500

refine_A0 = refine_L0**2 / 2
refine_A1 = refine_L1**2 / 2

# smooth angles
min_angle = 20


# Note that, by default, we tend to work in the DayMet CRS because this allows us to avoid
# reprojecting meteorological forcing datasets.
crs = watershed_workflow.crs.default_crs

# Load data from previous run

In [7]:
watershed_polys = gpd.read_parquet(fromOutput('01_watershed_polys.parquet'))
reaches = gpd.read_parquet(fromOutput('01_rivers.parquet'))

In [8]:
watershed_polys

,geometry,station_nm,dec_lat_va,dec_long_va,alt_va,alt_acy_va,alt_datum_cd,huc_cd,begin_date,end_date,units,tz,ID,count,comid,measure,name,reach_ID,river_index,reach_index,location_on_reach,true_geometry,incremental_catchment,true_gage_geometry,outlet
23,"POLYGON ((-2305777.792 2037720.003, -2305971.4...",Russian River Outlet,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,RR-outlet,NaN,8272933,0.0000,RR-outlet,8272933,0,0,0,POINT (-2313594.047 2045820.756),"POLYGON ((-2305777.792 2037720.003, -2305971.4...",POINT (-2313594.047 2045820.756),POINT (-2313594.047 2045820.756)
21,"POLYGON ((-2296796.653 2031061.892, -2296895.0...","Russian R A Hacienda Bridge Nr Guerneville, CA",38.508482,-122.927734,22.33,0.16,NAVD88,18010110,1939-10-01,2025-11-25,mm/day,UTC,USGS-11467000,9461.0,8272725,84.0061,USGS-11467000,8272725,0,40,1,POINT (-2295059.53 2047164.785),"POLYGON ((-2296796.653 2031061.892, -2296895.0...",POINT (-2295059.53 2047164.785),POINT (-2294250.425 2047087.173)
10,"POLYGON ((-2282295.004 2053875.042, -2282306.1...","Russian R Nr Healdsburg, CA",38.613203,-122.836345,79.98,0.26,NAVD88,18010110,1939-10-01,2025-11-25,mm/day,UTC,USGS-11464000,9461.0,8272379,89.9621,USGS-11464000,8272379,0,135,1,POINT (-2284208.116 2056234.303),"POLYGON ((-2282295.004 2053875.042, -2282306.1...",POINT (-2284208.116 2056234.303),POINT (-2283791.112 2056134.658)
8,"POLYGON ((-2282169.29 2061204.75, -2282340.484...","Russian R A Jimtown, CA",38.658202,-122.829401,143.70,0.26,NAVD88,18010110,2009-07-01,2025-11-25,mm/day,UTC,USGS-11463682,5327.0,8272211,90.8312,USGS-11463682,8272211,0,152,1,POINT (-2282227.758 2060911.556),"POLYGON ((-2282169.29 2061204.75, -2282340.484...",POINT (-2282227.758 2060911.556),POINT (-2282342.202 2061057.323)
7,"POLYGON ((-2287362.021 2074784.464, -2287412.6...","Russian R A Geyserville, CA",38.712645,-122.895792,165.68,0.26,NAVD88,18010110,1910-10-01,2025-11-25,mm/day,UTC,USGS-11463500,4596.0,8272107,28.1658,USGS-11463500,8272107,0,158,1,POINT (-2286019.829 2068367.397),"POLYGON ((-2287362.021 2074784.464, -2287412.6...",POINT (-2286019.829 2068367.397),POINT (-2287482.499 2070478.45)
4,"POLYGON ((-2299493.378 2094164.414, -2299640.0...","Russian R Nr Cloverdale, CA",38.879308,-123.053577,374.64,0.16,NAVD88,18010110,1951-08-01,2025-11-25,mm/day,UTC,USGS-11463000,9459.0,8271445,82.7127,USGS-11463000,8271445,0,187,1,POINT (-2293821.342 2090102.265),"POLYGON ((-2299493.378 2094164.414, -2299640.0...",POINT (-2293821.342 2090102.265),POINT (-2293880.874 2090543.664)
3,"POLYGON ((-2299591.085 2107888.87, -2299735.69...","Russian R Nr Hopland, CA",39.026527,-123.130525,500.01,0.26,NAVD88,18010110,1939-10-01,2025-11-25,mm/day,UTC,USGS-11462500,9461.0,8269119,91.8680,USGS-11462500,8269119,0,218,1,POINT (-2295520.729 2107795.032),"POLYGON ((-2299591.085 2107888.87, -2299735.69...",POINT (-2295520.729 2107795.032),POINT (-2295539.859 2108307.778)
2,"POLYGON ((-2298014.974 2118944.952, -2298210.8...","Russian R Nr Talmage, CA",39.112913,-123.183028,545.95,0.16,NAVD88,18010110,2009-08-06,2025-11-25,mm/day,UTC,USGS-11462080,5956.0,8268521,11.7142,USGS-11462080,8268521,0,235,0,POINT (-2297109.406 2118353.355),"POLYGON ((-2298014.974 2118944.952, -2298210.8...",POINT (-2297109.406 2118353.355),POINT (-2297141.368 2118153.588)
14,"POLYGON ((-2287719.891 2054198.95, -2287880.08...","Dry C Nr Mouth Nr Healdsburg, CA",38.587370,-122.862178,56.70,0.16,NAVD88,18010110,1981-10-01,2025-11-25,mm/day,UTC,USGS-11465350,7790.0,8272363,2.3004,USGS-11465350,8272363,0,55,0,POINT (-2287155.73 2054074.887),"POLYGON ((-2287719.891 2054198.95, -2287880.08...",POINT (-2287155.73 2054074.887),POINT (-2287131.618 2054099.621)
13,"POLYGON ((-2292170.937 2062428.575, -2292194.9...","Dry C Blw Lambert Br Nr Geyserville, CA",38.653202,-122.927181,112.03,0.16,NAVD88,18010110,2011-11-10,2025-11-25,mm/day,UTC,USGS-11465240,4778.0,8272227,68.2805,USGS-11465240,8272227,0,66,1,POINT (-2290478.701 2062725.744),"POLYGON ((-2292170.937 2062428.575, -2292194.9...",POINT (-2290478.701 2062725.744),POINT (-2290463.565 2062835.084)
12,"POLYGON ((-2298232.619 2060872.063, -2298352.6...","Dry C Nr Geyserville, CA",38.698521,-122.958054,160.49,0.16,NAVD88,18010110,1959-10-01,2024-06-27,mm/day,UTC,USGS-11465200,8309.0,8272125,48.9640,USGS-11465200,8272125,0,70,1,POINT (-2291612.329 2068346.918),"POLYGON ((-2298232.619 2060872.063, -2298352.6...",POINT (-2291612.329 2068346.918),POINT (-2291865.2 2068762.263)
20,"POLYGON ((-2290578.287 2035848.261, -2290525.2...","Mark West C Nr Mirabel Heights, CA",38.494039,-122.853288,2.28,0.16,NAVD88,18010110,2005-10-01,2025-11-25,mm/day,UTC,USGS-11466800,6580.0,8273161,90.6480,USGS-11466800,8273161,0,401,1,POINT (-2289335.848 2043814.587),"POLYGON ((-2290578.287 2035848.261, -2290525.2...",POINT (-2289335.848 2043814.587),POINT (-2288929.575 2043952.771)
11,"POLYGON ((-2305531.652 2067091.588, -2305497.7...","Dry C Bl Warm Springs Dam Nr Geyserville, CA",38.719632,-123.000556,NaN,NaN,,18010110,1939-10-01,2011-10-09,mm/day,UTC,USGS-11465000,4300.0,8272083,43.8600,USGS-11465000,8272083,0,86,1,POINT (-2294464.301 2071643.993),"POLYGON ((-2305531.652 2067091.588, -2305497.7...",POINT (-2294464.301 2071643.993),POINT (-2294556.95 2071497.385)
0,"POLYGON ((-2296020.275 2128290.375, -2296252.3...","Russian R Nr Ukiah, CA",39.195447,-123.195005,602.25,0.16,NAVD88,18010110,1911-10-01,2022-09-30,mm/day,UTC,USGS-11461000,7200.0,8269099,42.3900,USGS-11461000,8269099,0,257,1,POINT (-2295482.62 2127517.048),"POLYGON ((-2296020.275 2128290.375, -2296252.3...",POINT (-2295482.62 2127517.048),POINT (-2295808.202 2128498.772)
1,"POLYGON ((-2287035.002 2125004.968, -2287066.7...","Ef Russian R Nr Calpella, CA",39.246523,-123.130251,790.74,0.26,NAVD88,18010110,1941-10-01,2025-11-25,mm/day,UTC,USGS-11461500,9461.0,8269091,93.5630,USGS-11461500,8269091,0,310,1,POINT (-2288554.228 2131447.502),"POLYGON ((-2287035.002 2125004.968, -2287066.7...",POINT (-2288554.228 2131447.502),POINT (-2288414.601 2131507.585)
6,"POLYGON ((-2283781.117 2073298.807, -2284028.0...","Big Sulphur C Nr Cloverdale, CA",38.825976,-122.996908,302.75,0.16,NAVD88,18010110,1957-07-01,2025-11-25,mm/day,UTC,USGS-11463200,7479.0,8271875,76.1110,USGS-11463200,8271875,0,357,1,POINT (-2290821.963 2082997.741),"MULTIPOLYGON (((-2283781.117 2073298.807, -228...",POINT (-2290821.963 2082997.741),POINT (-2290300.314 2083112.99)
22,"POLYGON ((-2307987.231 2050502.657, -2308022.7...","Austin C Nr Cazadero, CA",38.506536,-123.069683,43.52,0.16,NAVD88,18010110,1959-06-01,2025-11-25,mm/day,UTC,USGS-11467200,7693.0,8271049,60.2698,USGS-11467200,8271049,0,9,1,POINT (-2306891.006 2050392.33),"POLYGON ((-2307987.231 2050502.657, -2308022.7...",POINT (-2306891.006 2050392.33),POINT (-2306649.065 2050708.156)
19,"POLYGON ((-2280928.918 2034481.167, -2281249.6...","Santa Rosa C A Willowside Rd Nr Santa Rosa, CA",38.445190,-122.807213,2.36,0.16,NAVD88,18010110,1998-12-09,2025-11-25,mm/day,UTC,USGS-11466320,9369.0,8273639,100.0000,USGS-11466320,8273639,0,430,1,POINT (-2287036.692 2037446.722),"POLYGON ((-2280928.918 2034481.167, -2281249.6...",POINT (-2287036.692 2037446.722),POINT (-2286686.815 2037377.161)
16,"POLYGON ((-2283669.283 2028359.279, -2283832.8...","Laguna De Santa Rosa C Nr Sebastopol, CA",38.425469,-122.829158,0.00,0.01,NAVD88,18010110,1998-11-18,2025-11-25,mm/day,UTC,USGS-11465750,7964.0,8273287,81.8632,USGS-11465750,8273287,0,445,1,POINT (-2289474.773 2035852.052),"POLYGON ((-2283669.283 2028359.279, -2283832.8...",POINT (-2289474.773 2035852.052),POINT (-2289453.405 2035693.699)
9,"POLYGON ((-2270136.464 2054249.77, -2270353.33...","Maacama C Nr Kellogg, CA",38.640981,-122.763843,179.62,0.16,NAVD88,18010110,1961-01-01,2025-11-25,mm/day,UTC,USGS-11463900,3758.0,8272605,29.5054,USGS-11463900,8272605,0,383,1,POINT (-2277336.013 2057484.827),"POLYGON ((-2270136.464 2054249.77, -2270353.33...",POINT (-2277336.013 2057484.827),POINT (-2275843.982 2057040.465)
18,"POLYGON ((-2272619.126 2029350.828, -2272815.0...","Santa Rosa C A Santa Rosa, CA",38.436541,-122.724673,102.43,0.16,NAVD88,18010110,1939-10-01,2025-11-25,mm/day,UTC,USGS-11466200,5117.0,8273645,80.5508,USGS-11466200,8273645,0,433,1,POINT (-2280450.806 2034531.903),"POLYGON ((-2272619.126 2029350.828, -2272815.0...",POINT (-2280450.806 2034531.903),POINT (-2279389.588 2034314.587)
15,"POLYGON ((-2284077.877 2020488.039, -2284124.4...","Laguna De Santa Rosa A Stony Pt Rd Nr Cotati, CA",38.352098,-122.744116,1.86,0.16,NAVD88,18010110,1998-11-06,2025-11-25,mm/day,UTC,USGS-11465680,8608.0,8273659,86.3794,USGS-11465680,8273659,0,451,1,POINT (-2284694.536 2025906.037),"POLYGON ((-2284077.877 2020488.039, -2284124.4...",POINT (-2284694.536 2025906.037),POINT (-2284319.359 2025827.84)
17,"POLYGON ((-2271727.659 2021763.029, -2271828.4...","Matanzas C A Santa Rosa, CA",38.438763,-122.702450,2.48,0.16,NAVD88,18010110,2004-10-01,2025-11-25,mm/day,UTC,USGS-11466170,4529.0,948010118,11.4753,USGS-11466170,948010118,0,439,1,POINT (-2278535.621 2034238.183),"POLYGON ((-2271727.659 2021763.029, -2271828.4...",POINT (-2278535.621 2034238.183),POINT (-2278309.097 2034179.325)
5,"POLYGON ((-2271338.668 2067036.801, -2271665.0...","Big Sulphur C A G Resort Nr Cloverdale, CA",38.797645,-122.802458,1429.88,0.16,NAVD88,18010110,1980-10-01,2025-11-25,mm/day,UTC,USGS-11463170,9461.0,8271917,32.4839,USGS-11463170,8271917,0,371,1,POINT (-2275647.163 2075276.831),"POLYGON ((-2271338.668 2067036.801, -2271665.0...",POINT (-2275647.163 2075276.831),POINT (-2275160.385 2074516.199)

In [9]:
# remove a few points that cause trouble later...
def removeSecondToLastCoordinate(reach_id):
    bad = reaches.index[reaches['ID'] == reach_id].values[0]
    
    old_ls = list(reaches.loc[bad, 'geometry'].coords)
    new_ls = shapely.geometry.LineString(old_ls[0:-2] + [old_ls[-1],])
    reaches.loc[bad, 'geometry'] = new_ls

removeSecondToLastCoordinate('8271033')
removeSecondToLastCoordinate('8272363')
removeSecondToLastCoordinate('8272363') # intentionally called twice


#removeSecondToLastCoordinate('8272379')
#removeSecondToLastCoordinate('8270663')
#removeSecondToLastCoordinate('8269099')
#removeSecondToLastCoordinate('8269105')
#removeSecondToLastCoordinate('8270661')
#removeSecondToLastCoordinate('8273681')
#removeSecondToLastCoordinate('8273681') # intentionally called twice
#removeSecondToLastCoordinate('8273271')

In [10]:
watershed_polys

,geometry,station_nm,dec_lat_va,dec_long_va,alt_va,alt_acy_va,alt_datum_cd,huc_cd,begin_date,end_date,units,tz,ID,count,comid,measure,name,reach_ID,river_index,reach_index,location_on_reach,true_geometry,incremental_catchment,true_gage_geometry,outlet
23,"POLYGON ((-2305777.792 2037720.003, -2305971.4...",Russian River Outlet,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,RR-outlet,NaN,8272933,0.0000,RR-outlet,8272933,0,0,0,POINT (-2313594.047 2045820.756),"POLYGON ((-2305777.792 2037720.003, -2305971.4...",POINT (-2313594.047 2045820.756),POINT (-2313594.047 2045820.756)
21,"POLYGON ((-2296796.653 2031061.892, -2296895.0...","Russian R A Hacienda Bridge Nr Guerneville, CA",38.508482,-122.927734,22.33,0.16,NAVD88,18010110,1939-10-01,2025-11-25,mm/day,UTC,USGS-11467000,9461.0,8272725,84.0061,USGS-11467000,8272725,0,40,1,POINT (-2295059.53 2047164.785),"POLYGON ((-2296796.653 2031061.892, -2296895.0...",POINT (-2295059.53 2047164.785),POINT (-2294250.425 2047087.173)
10,"POLYGON ((-2282295.004 2053875.042, -2282306.1...","Russian R Nr Healdsburg, CA",38.613203,-122.836345,79.98,0.26,NAVD88,18010110,1939-10-01,2025-11-25,mm/day,UTC,USGS-11464000,9461.0,8272379,89.9621,USGS-11464000,8272379,0,135,1,POINT (-2284208.116 2056234.303),"POLYGON ((-2282295.004 2053875.042, -2282306.1...",POINT (-2284208.116 2056234.303),POINT (-2283791.112 2056134.658)
8,"POLYGON ((-2282169.29 2061204.75, -2282340.484...","Russian R A Jimtown, CA",38.658202,-122.829401,143.70,0.26,NAVD88,18010110,2009-07-01,2025-11-25,mm/day,UTC,USGS-11463682,5327.0,8272211,90.8312,USGS-11463682,8272211,0,152,1,POINT (-2282227.758 2060911.556),"POLYGON ((-2282169.29 2061204.75, -2282340.484...",POINT (-2282227.758 2060911.556),POINT (-2282342.202 2061057.323)
7,"POLYGON ((-2287362.021 2074784.464, -2287412.6...","Russian R A Geyserville, CA",38.712645,-122.895792,165.68,0.26,NAVD88,18010110,1910-10-01,2025-11-25,mm/day,UTC,USGS-11463500,4596.0,8272107,28.1658,USGS-11463500,8272107,0,158,1,POINT (-2286019.829 2068367.397),"POLYGON ((-2287362.021 2074784.464, -2287412.6...",POINT (-2286019.829 2068367.397),POINT (-2287482.499 2070478.45)
4,"POLYGON ((-2299493.378 2094164.414, -2299640.0...","Russian R Nr Cloverdale, CA",38.879308,-123.053577,374.64,0.16,NAVD88,18010110,1951-08-01,2025-11-25,mm/day,UTC,USGS-11463000,9459.0,8271445,82.7127,USGS-11463000,8271445,0,187,1,POINT (-2293821.342 2090102.265),"POLYGON ((-2299493.378 2094164.414, -2299640.0...",POINT (-2293821.342 2090102.265),POINT (-2293880.874 2090543.664)
3,"POLYGON ((-2299591.085 2107888.87, -2299735.69...","Russian R Nr Hopland, CA",39.026527,-123.130525,500.01,0.26,NAVD88,18010110,1939-10-01,2025-11-25,mm/day,UTC,USGS-11462500,9461.0,8269119,91.8680,USGS-11462500,8269119,0,218,1,POINT (-2295520.729 2107795.032),"POLYGON ((-2299591.085 2107888.87, -2299735.69...",POINT (-2295520.729 2107795.032),POINT (-2295539.859 2108307.778)
2,"POLYGON ((-2298014.974 2118944.952, -2298210.8...","Russian R Nr Talmage, CA",39.112913,-123.183028,545.95,0.16,NAVD88,18010110,2009-08-06,2025-11-25,mm/day,UTC,USGS-11462080,5956.0,8268521,11.7142,USGS-11462080,8268521,0,235,0,POINT (-2297109.406 2118353.355),"POLYGON ((-2298014.974 2118944.952, -2298210.8...",POINT (-2297109.406 2118353.355),POINT (-2297141.368 2118153.588)
14,"POLYGON ((-2287719.891 2054198.95, -2287880.08...","Dry C Nr Mouth Nr Healdsburg, CA",38.587370,-122.862178,56.70,0.16,NAVD88,18010110,1981-10-01,2025-11-25,mm/day,UTC,USGS-11465350,7790.0,8272363,2.3004,USGS-11465350,8272363,0,55,0,POINT (-2287155.73 2054074.887),"POLYGON ((-2287719.891 2054198.95, -2287880.08...",POINT (-2287155.73 2054074.887),POINT (-2287131.618 2054099.621)
13,"POLYGON ((-2292170.937 2062428.575, -2292194.9...","Dry C Blw Lambert Br Nr Geyserville, CA",38.653202,-122.927181,112.03,0.16,NAVD88,18010110,2011-11-10,2025-11-25,mm/day,UTC,USGS-11465240,4778.0,8272227,68.2805,USGS-11465240,8272227,0,66,1,POINT (-2290478.701 2062725.744),"POLYGON ((-2292170.937 2062428.575, -2292194.9...",POINT (-2290478.701 2062725.744),POINT (-2290463.565 2062835.084)
12,"POLYGON ((-2298232.619 2060872.063, -2298352.6...","Dry C Nr Geyserville, CA",38.698521,-122.958054,160.49,0.16,NAVD88,18010110,1959-10-01,2024-06-27,mm/day,UTC,USGS-11465200,8309.0,8272125,48.9640,USGS-11465200,8272125,0,70,1,POINT (-2291612.329 2068346.918),"POLYGON ((-2298232.619 2060872.063, -2298352.6...",POINT (-2291612.329 2068346.918),POINT (-2291865.2 2068762.263)
20,"POLYGON ((-2290578.287 2035848.261, -2290525.2...","Mark West C Nr Mirabel Heights, CA",38.494039,-122.853288,2.28,0.16,NAVD88,18010110,2005-10-01,2025-11-25,mm/day,UTC,USGS-11466800,6580.0,8273161,90.6480,USGS-11466800,8273161,0,401,1,POINT (-2289335.848 2043814.587),"POLYGON ((-2290578.287 2035848.261, -2290525.2...",POINT (-2289335.848 2043814.587),POINT (-2288929.575 2043952.771)
11,"POLYGON ((-2305531.652 2067091.588, -2305497.7...","Dry C Bl Warm Springs Dam Nr Geyserville, CA",38.719632,-123.000556,NaN,NaN,,18010110,1939-10-01,2011-10-09,mm/day,UTC,USGS-11465000,4300.0,8272083,43.8600,USGS-11465000,8272083,0,86,1,POINT (-2294464.301 2071643.993),"POLYGON ((-2305531.652 2067091.588, -2305497.7...",POINT (-2294464.301 2071643.993),POINT (-2294556.95 2071497.385)
0,"POLYGON ((-2296020.275 2128290.375, -2296252.3...","Russian R Nr Ukiah, CA",39.195447,-123.195005,602.25,0.16,NAVD88,18010110,1911-10-01,2022-09-30,mm/day,UTC,USGS-11461000,7200.0,8269099,42.3900,USGS-11461000,8269099,0,257,1,POINT (-2295482.62 2127517.048),"POLYGON ((-2296020.275 2128290.375, -2296252.3...",POINT (-2295482.62 2127517.048),POINT (-2295808.202 2128498.772)
1,"POLYGON ((-2287035.002 2125004.968, -2287066.7...","Ef Russian R Nr Calpella, CA",39.246523,-123.130251,790.74,0.26,NAVD88,18010110,1941-10-01,2025-11-25,mm/day,UTC,USGS-11461500,9461.0,8269091,93.5630,USGS-11461500,8269091,0,310,1,POINT (-2288554.228 2131447.502),"POLYGON ((-2287035.002 2125004.968, -2287066.7...",POINT (-2288554.228 2131447.502),POINT (-2288414.601 2131507.585)
6,"POLYGON ((-2283781.117 2073298.807, -2284028.0...","Big Sulphur C Nr Cloverdale, CA",38.825976,-122.996908,302.75,0.16,NAVD88,18010110,1957-07-01,2025-11-25,mm/day,UTC,USGS-11463200,7479.0,8271875,76.1110,USGS-11463200,8271875,0,357,1,POINT (-2290821.963 2082997.741),"MULTIPOLYGON (((-2283781.117 2073298.807, -228...",POINT (-2290821.963 2082997.741),POINT (-2290300.314 2083112.99)
22,"POLYGON ((-2307987.231 2050502.657, -2308022.7...","Austin C Nr Cazadero, CA",38.506536,-123.069683,43.52,0.16,NAVD88,18010110,1959-06-01,2025-11-25,mm/day,UTC,USGS-11467200,7693.0,8271049,60.2698,USGS-11467200,8271049,0,9,1,POINT (-2306891.006 2050392.33),"POLYGON ((-2307987.231 2050502.657, -2308022.7...",POINT (-2306891.006 2050392.33),POINT (-2306649.065 2050708.156)
19,"POLYGON ((-2280928.918 2034481.167, -2281249.6...","Santa Rosa C A Willowside Rd Nr Santa Rosa, CA",38.445190,-122.807213,2.36,0.16,NAVD88,18010110,1998-12-09,2025-11-25,mm/day,UTC,USGS-11466320,9369.0,8273639,100.0000,USGS-11466320,8273639,0,430,1,POINT (-2287036.692 2037446.722),"POLYGON ((-2280928.918 2034481.167, -2281249.6...",POINT (-2287036.692 2037446.722),POINT (-2286686.815 2037377.161)
16,"POLYGON ((-2283669.283 2028359.279, -2283832.8...","Laguna De Santa Rosa C Nr Sebastopol, CA",38.425469,-122.829158,0.00,0.01,NAVD88,18010110,1998-11-18,2025-11-25,mm/day,UTC,USGS-11465750,7964.0,8273287,81.8632,USGS-11465750,8273287,0,445,1,POINT (-2289474.773 2035852.052),"POLYGON ((-2283669.283 2028359.279, -2283832.8...",POINT (-2289474.773 2035852.052),POINT (-2289453.405 2035693.699)
9,"POLYGON ((-2270136.464 2054249.77, -2270353.33...","Maacama C Nr Kellogg, CA",38.640981,-122.763843,179.62,0.16,NAVD88,18010110,1961-01-01,2025-11-25,mm/day,UTC,USGS-11463900,3758.0,8272605,29.5054,USGS-11463900,8272605,0,383,1,POINT (-2277336.013 2057484.827),"POLYGON ((-2270136.464 2054249.77, -2270353.33...",POINT (-2277336.013 2057484.827),POINT (-2275843.982 2057040.465)
18,"POLYGON ((-2272619.126 2029350.828, -2272815.0...","Santa Rosa C A Santa Rosa, CA",38.436541,-122.724673,102.43,0.16,NAVD88,18010110,1939-10-01,2025-11-25,mm/day,UTC,USGS-11466200,5117.0,8273645,80.5508,USGS-11466200,8273645,0,433,1,POINT (-2280450.806 2034531.903),"POLYGON ((-2272619.126 2029350.828, -2272815.0...",POINT (-2280450.806 2034531.903),POINT (-2279389.588 2034314.587)
15,"POLYGON ((-2284077.877 2020488.039, -2284124.4...","Laguna De Santa Rosa A Stony Pt Rd Nr Cotati, CA",38.352098,-122.744116,1.86,0.16,NAVD88,18010110,1998-11-06,2025-11-25,mm/day,UTC,USGS-11465680,8608.0,8273659,86.3794,USGS-11465680,8273659,0,451,1,POINT (-2284694.536 2025906.037),"POLYGON ((-2284077.877 2020488.039, -2284124.4...",POINT (-2284694.536 2025906.037),POINT (-2284319.359 2025827.84)
17,"POLYGON ((-2271727.659 2021763.029, -2271828.4...","Matanzas C A Santa Rosa, CA",38.438763,-122.702450,2.48,0.16,NAVD88,18010110,2004-10-01,2025-11-25,mm/day,UTC,USGS-11466170,4529.0,948010118,11.4753,USGS-11466170,948010118,0,439,1,POINT (-2278535.621 2034238.183),"POLYGON ((-2271727.659 2021763.029, -2271828.4...",POINT (-2278535.621 2034238.183),POINT (-2278309.097 2034179.325)
5,"POLYGON ((-2271338.668 2067036.801, -2271665.0...","Big Sulphur C A G Resort Nr Cloverdale, CA",38.797645,-122.802458,1429.88,0.16,NAVD88,18010110,1980-10-01,2025-11-25,mm/day,UTC,USGS-11463170,9461.0,8271917,32.4839,USGS-11463170,8271917,0,371,1,POINT (-2275647.163 2075276.831),"POLYGON ((-2271338.668 2067036.801, -2271665.0...",POINT (-2275647.163 2075276.831),POINT (-2275160.385 2074516.199)

In [11]:
print(len(reaches))
rivers = watershed_workflow.river_tree.createRivers(reaches, method='native')
print(len(rivers))

470
1

In [12]:
# mark the outlet reaches as do-not-merge
for river in rivers:
    river.df['do-not-merge'] = [0,] * len(river)

roots = [rivers[watershed_polys.loc[index, 'river_index']].getNode(watershed_polys.loc[index, 'reach_index'])
             for index in watershed_polys.index]
for outlet, root in zip(watershed_polys.index, roots):
    if watershed_polys.loc[outlet].location_on_reach == 0:
        root['do-not-merge'] = -1
    elif watershed_polys.loc[outlet].location_on_reach == 1:
        root['do-not-merge'] = 1
    else:
        assert False

## Compute disjoint subcatchments

In [13]:
watersheds = watershed_workflow.split_hucs.SplitHUCs(watershed_polys)

2026-02-09 13:04:55,658 - root - INFO: Removing holes on 24 polygons
2026-02-09 13:04:55,658 - root - INFO:   -- removed interior
2026-02-09 13:04:55,669 - root - INFO:   -- union
2026-02-09 13:04:55,670 - root - INFO: Parsing 1 components for holes
2026-02-09 13:04:55,670 - root - INFO:   -- complete

In [18]:
watersheds.df['comid'] = watersheds.df['comid'].astype(int)

In [21]:
# this generates a zoomable map, showing different reaches and watersheds, 
# with discrete points.  Problem areas are clickable to get IDs for manual
# modifications.
m = watersheds.explore('comid', 
                       marker=False, marker_size=10)

for river in rivers:
    m = river.explore(column=None, m=m, color='black', name=river['name'], marker=False, marker_size=10)

#m = gpd.GeoDataFrame(geometry=[shapely.geometry.Point(point)], crs=watersheds.crs).explore(m=m, color='k', marker_size=100)

m = watershed_workflow.makeMap(m)
m

#fig, ax = plt.subplots(1,1)
#watersheds.plot(ax=ax, color='k')
#rivers[0].plot(ax=ax, color='b')
#plt.show()

In [ ]:
# remove bad points on watersheds
old_ls = list(watersheds.linestrings[30].coords)
new_ls = shapely.geometry.LineString(old_ls[0:80]+old_ls[85:])
watersheds.linestrings[30] = new_ls


old_ls = list(watersheds.linestrings[44].coords)
new_ls = shapely.geometry.LineString(old_ls[0:96]+old_ls[97:])
watersheds.linestrings[44] = new_ls

# must update as we have modified geometry
watersheds.update()

In [ ]:
# simplifying 
watershed_workflow.simplify(watersheds, rivers, 
                            reach_segment_target_length=refine_L0,
                            huc_segment_target_length=refine_L1,
                            river_close_distance=refine_d0,
                            river_far_distance=refine_d1,
                            snap_triple_junctions_tol=refine_L0,
                            min_angle=min_angle,
                            junction_min_angle=min_angle
                           )

# greatly shrunk the rivers... shrink the dataframe too
for river in rivers:
    river.resetDataFrame()

In [ ]:
watersheds.df

In [ ]:
# this generates a zoomable map, showing different reaches and watersheds, 
# with discrete points.  Problem areas are clickable to get IDs for manual
# modifications.
m = watersheds.explore(marker=True, marker_size=10)

for river in rivers:
    m = river.explore(column=None, m=m, color='black', name=river['name'], marker=True, marker_size=10)

m = watershed_workflow.makeMap(m)
m

In [ ]:
# move one last point... Santa Rosa does weird stuff...
old_ls = list(watersheds.linestrings[57].coords)
new_ls = shapely.geometry.LineString(old_ls[:-1] + [list(watersheds.linestrings[62].coords)[7],])
watersheds.linestrings[57] = new_ls

watersheds.update()

In [ ]:
# save this final version of rivers and watersheds to disk
import pickle
with open(toOutput('watershed_polys', '02_watersheds.pickle'), 'wb') as fid:
    pickle.dump(watersheds, fid)

river_df = gpd.GeoDataFrame(pd.concat([r.to_dataframe() for r in rivers]), crs=crs)
river_df.to_parquet(toOutput('rivers', '02_rivers.parquet'))

In [ ]:
# save output filenames
with open(toOutput('02_output_filenames', '02_output_filenames.txt'), 'wb') as fid:
    pickle.dump(output_filenames, fid)